events {
}

http {
    server {

        location /node-server {
            proxy_pass http://node-backend:4000;
        }

        location /python-server {
            proxy_pass http://python-backend:5000;
        }
    }
}